name: Call other workflow
on:
  workflow_dispatch:

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2

      - name: call
        uses: ./.github/workflows/inputs_sample.yml@main
        with:
          name: hogehoge
          env: qas
          dry_run: false
