name: Checkout Sample
on:
  workflow_dispatch:

jobs:
  checkout-and-ls:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2

      - name: Exec ls command
        run: |
          ls -al
          cd .github/workflows/
          ls -al

  checkout-other-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Get golang
        uses: actions/checkout@v2
        with:
          repository: golang/go  #チェックアウトするレポジトリ(ここではhttps://github.com/golang/goをチェックアウト)
          path: another_repo     #どこにチェックアウトするか
          ref: master            #レポジトリのブランチ

      - name: Exec ls command
        run: |
          ls -al
          cd another_repo
          ls -al
