name: Inputs Sample
on:
  #マニュアル実行
  workflow_dispatch:
    inputs:
      name:
        description: '名前'
        required: true
        default: 'hoge'
      env:
        description: '環境'
        required: true
        type: choice
        default: 'dev'
        options:
          - "dev"
          - "stg"
          - "prd"
      dry_run:
        description: 'ドライランモード'
        required: true
        type: boolean

  #別のワークフローから実行
  workflow_call:
    inputs:
      name:
        description: '名前'
        required: true
        type: string
        default: 'hoge'
      env:
        description: '環境'
        required: true
        type: string
      dry_run:
        description: 'ドライランモード'
        required: true
        type: boolean

jobs:
  input-sample:
    runs-on: ubuntu-latest
    steps:
      - name: Get inputs
        run: |
          echo name is ${{ inputs.name }}
          echo env is ${{ inputs.env }}
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            echo dry_run mode.
          else
            echo normal mode.
          fi

