name: Invoke other workflow
on:
  workflow_dispatch:

jobs:
  invoke-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Checkout Sample
#        inputs: '{ "xxx": "xxx" }'  呼び出すワークフローにinputがある場合


