name: Needs Sample
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test2"

  job3:
    if: ${{ needs.job2.result }} = "success"
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test3"

  job4:
    if: ${{ needs.job2.result }} = "success"
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test4"

  job5:
    needs: [job3, job4]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test5"


