name: Repository Dispatch Sample

on: repository_dispatch

#以下のようにAPI実行することでこのworkflowが実行される
# curl -X POST https://api.github.com/repos/:owner/:repo/dispatches \
#   -H 'Accept: application/vnd.github.everest-preview+json' \
#   -u user_name:personal_access_token \
#   --data '{"event_type": "your_event", "client_payload": { "message": "hello world" }}'

jobs:
  repo-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event is '${{ github.event.action }}'"                    #リクエストボディのevent_type
          echo "Message is '${{ github.event.client_payload.message }}'"  #リクエストボディのclient_payload
