name: Manual Workflow Sample 1
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'input your name.'
        default: 'hoge'
        required: true

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - name: Get name
        run: |
          echo ${{ github.event.inputs.name }}

  checkout-and-ls:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2

      - name: Exec ls command
        run: |
          ls -al
          cd .github/workflows/
          ls -al

  checkout-other-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Get golang
        uses: actions/checkout@v2
        with:
          repository: golang/go
          path: another_repo
          ref: master

      - name: Exec ls command
        run: |
          ls -al
          cd another_repo
          ls -al
