name: Manual Workflow Sample 1
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'input your name.'
        default: 'hoge'
        required: true
env:
  TEST1: ${{secrets.SECRET_TEST}}  #secretの取得. TEST1のスコープは全体

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - name: Get name
        run: |
          echo ${{ github.event.inputs.name }}

  checkout-and-ls:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2

      - name: Exec ls command
        run: |
          ls -al
          cd .github/workflows/
          ls -al

  checkout-other-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Get golang
        uses: actions/checkout@v2
        with:
          repository: golang/go  #チェックアウトするレポジトリ(ここではhttps://github.com/golang/goをチェックアウト)
          path: another_repo     #どこにチェックアウトするか
          ref: master            #レポジトリのブランチ

      - name: Exec ls command
        run: |
          ls -al
          cd another_repo
          ls -al

  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Get secret
        env:
          TEST2: ${{secrets.SECRET_TEST}}  #secretの取得. TEST2のスコープはこのジョブ
        run: |
          echo "TEST1 is ${{ $TEST1}}"
          echo "TEST2 is ${{ $TEST2}}"
