name: Manual Workflow Sample 1
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'input your name.'
        default: 'hoge'
        required: true

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - name: Get name
        run: |
          echo ${{ github.event.inputs.name }}

  checkout-and-ls:
    runs-on: ubuntu-latest
    steps:
      - name: Get source and exec ls command
        uses: actions/checkout@v2
        run: |
          ls -al
          cd .github/workflows/
          ls -al
