name: Secrets Sample
on:
  workflow_dispatch:
    inputs:
      env:
        description: '環境'
        required: true
        type: choice
        default: 'dev'
        options:
          - "dev"
          - "stg"
          - "prd"

jobs:
  get-repository-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Get secret
        run: |
          echo ${{ secrets.REPOSITORY_SECRET_TEST }}                  #secretをechoしても*でマスクされて表示される
          echo ${{ secrets.REPOSITORY_SECRET_TEST }} | sed 's/./& /g' #ただしsedでスペースを挟めば表示できる

  get-environment-secret:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
    steps:
      - name: Get secret
        run: |
          echo ${{ secrets.ENVIRONMENT_SECRET_TEST }}                  #secretをechoしても*でマスクされて表示される
          echo ${{ secrets.ENVIRONMENT_SECRET_TEST }} | sed 's/./& /g' #ただしsedでスペースを挟めば表示できる
