name: trivy code scanning
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  scan-and-upload:
    name: Scan and Uplaod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

# ファイルをartifactsに保存する場合 
#      - name: Upload Trivy scan results to artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: trivy-results-sarif
#          path: ./trivy-results.sarif
