#workflow-run_sample1の完了をトリガーに実行されるaction

name: Run Sample 2

on:
  workflow_run:
    workflows: [Run Sample 1]
    types:
      - completed

jobs:
  on-success:
  #workflow-run_sample1が成功時はこのjobが実行
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: success
        run: |
          echo "success"

  on-failure:
  #workflow-run_sample1が失敗時はこのjobが実行
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: failure
        run: |
          echo "failure"